name: Test-All-Daily

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'  # Автозапуск по расписанию (ежедневно в полночь)

permissions:
  contents: write  # Нужен для публикации отчёта в gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests and generate Allure results
        run: |
          pytest -s -v --alluredir=allure-results
        continue-on-error: true

      - name: Add Allure metadata
        working-directory: allure-results
        if: always()
        run: |
          echo GIT_BRANCH=${{ github.head_ref || github.ref_name }} >> environment.properties
          echo GIT_COMMIT_ID=${{ github.sha }} >> environment.properties
          echo GIT_COMMIT_MESSAGE=$(git show -s --format=%s HEAD) >> environment.properties
          echo GIT_COMMIT_AUTHOR_NAME=$(git show -s --format='%ae' HEAD) >> environment.properties
          echo GIT_COMMIT_TIME=$(git show -s --format=%ci HEAD) >> environment.properties

      - name: Checkout previous Allure history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy history to results
        if: always()
        run: |
          mkdir -p allure-results/history
          cp -r gh-pages/history/* allure-results/history/ || echo "No previous history found"

      - name: Generate Allure report with history
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 50

      - name: Publish Allure report to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          personal_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
